use_frameworks!

platform :ios, '10.0'

target 'XCAppKit_Example' do
  pod 'XCAppKit', :path => '../'

  target 'XCAppKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
